Update post_install

diff --git a/post_install b/post_install
--- a/post_install
+++ b/post_install
@@ -2,7 +2,7 @@
 
 is_installed(){
 	if ! [ -x "$(command -v $1)" ]; then
-	  echo 'Error: $1 is not installed.' >&2
+	  echo "Error: $1 is not installed." >&2
 	  exit 1
 	fi
 }
